---
- name: run QUIC multi stream
  hosts: loadgen
  tasks:
    - name: render traffic file for quic multi
      become: true
      become_user: root
      template:
        src:
          traffic_file/quic_multi.json
        dest:
          /root/emqtt-bench/topic_spec.json

    - name: run the test
      become: true
      become_user: root
      shell: |
        cd /root/emqtt-bench/;
        . /home/runner/OTP/default/activate
        [ ! -f /root/emqtt-bench/emqtt_bench ] && make;
        set +e
        source with-ipaddrs.sh || echo "ok"
        ./emqtt_bench pub -h lb.int.william --topics-payload ./topic_spec.json -p 14567 --quic true -k 0 -c 6000 -x 30 --ifaddr $ipaddrs;
      args:
        executable: /bin/bash
