---
- name: run TLS
  hosts: loadgen
  tasks:
    - name: render traffic file
      become: true
      become_user: root
      template:
        src:
          traffic_file/tls.json
        dest:
          /root/emqtt-bench/topic_spec.json

    - name: run the test
      become: true
      become_user: root
      shell: |
        . /home/runner/OTP/default/activate
        cd /root/emqtt-bench/;
        [ ! -f /root/emqtt-bench/emqtt_bench ] && make;
        which erl
        source with-ipaddrs.sh || echo "ok"
        ./emqtt_bench pub -h lb.int.william --topics-payload ./topic_spec.json -S -p 8883 -k 0 -c 5000 -x 30
      args:
        executable: /bin/bash
