[bastion]
# get bastion host from aws cli output
bastion_host ansible_user=ec2-user ansible_host=13.60.242.97

[emqx]
emqx-0 ansible_host=emqx-0.int.william
emqx-1 ansible_host=emqx-1.int.william
emqx-2 ansible_host=emqx-2.int.william

[loadgen]
loadgen-0 ansible_host=loadgen-0.int.william
loadgen-1 ansible_host=loadgen-1.int.william
loadgen-2 ansible_host=loadgen-2.int.william
loadgen-3 ansible_host=loadgen-3.int.william

[all:vars]
ansible_user=ubuntu
ansible_ssh_common_args='-p 22 -o ProxyCommand="ssh -W %h:%p -q ec2-user@13.60.242.97"'
ansible_ssh_extra_args='-o StrictHostKeyChecking=no'
